# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TapThemeManager2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TapFontKit-iOS'
  pod 'LocalisationManagerKit-iOS'
  # Pods for TapThemeManager2020

end

target 'TapThemeManagerObjCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapThemeManagerObjCDemo

end

target 'TapThemeManagerSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for TapThemeManagerSwiftDemo

end
